### ISSUE TITLE
The SeriesInstanceUID doesn't match

### ISSUE THREAD

**Issue by LAX1992** [neuro-ml/vertebral-fractures-severity#1]
After download the MoscowRadiology-CTLungCa-500 dataset, I tried to matching the annotation with images through DICOM tag "SeriesInstanceUID" but can't find the corresponding one.
The prefix of SeriesInstanceUID from json file in annotation folder is 1.2.276, while the SeriesInstanceUID from DICOM is 1.2.643 hence I can't load image through example.py.
Please help if the annotation files are marked incorrectly, thanks.

**Comment by maxme1** [comment]
Hi!
Apparently, the dataset version was changed after the paper submission. I downloaded the new version and tried to manually match the old and new version, just in case the UIDs were randomly generated, but it looks like the data did change.
We'll contact our colleagues that published the new version and try to sort this out. It should take a while. Maybe 1-2 weeks.

**Comment by mrahmansagar** [comment]
Is there any update regarding updated annotations?

**Comment by maxme1** [comment]
Yes! We finally managed to match the data between the versions. It took more time than we expected, because some cases had to be matched manually. Sorry for the delay.

**Comment by LAX1992** [comment]
Thanks for all your hard work.

**Comment by mrahmansagar** [comment]
Thank you @maxme1 for the update. I tried with the example.py and it dose work accordingly. 👍

**Comment by maxme1** [comment]
Great! Closing the issue for now. Feel free to (re)open if you have any questions.
