### ISSUE TITLE
Dataset linked website is 404

### ISSUE THREAD

**Issue by zhibaishouheilab** [neuro-ml/vertebral-fractures-severity#4]
I have found the website linked to the dataset is no longer working. Could you please provide a new way to download the data? Appreciate it！

**Comment by maxme1** [comment]
Hi! Yes, it happens all the time, and unfortunately there's nothing we can do about it.
However I managed to find [the new link](https://mosmed.ai/en/datasets/mosmeddata-kt-s-priznakami-raka-legkogo-tip-viii/). This should be the same dataset. Can you please try it?

**Comment by zhibaishouheilab** [comment]
Thanks a lot! This link works, but when I download it I get an error! Want to ask if this has happened to you?

**Comment by maxme1** [comment]
Hmmm. What error are you getting? Can you send a screenshot maybe?

**Comment by zhibaishouheilab** [comment]
When I clicked the download and entered my email, I got the following error 
<img width="943" alt="error" src="https://github.com/neuro-ml/vertebral-fractures-severity/assets/57787017/c8433b0e-c3d8-414e-b8f8-0c9054021fb0">

**Comment by maxme1** [comment]
Hi! Sorry, I've been on vacation the whole week. I tried to do the same thing and it went fine. Maybe you could use another email, or use a vpn? This is a Russian site, so maybe it is partially blocked in your region. 
Let me know if it doesn't help, I might have another idea.

**Comment by zhibaishouheilab** [comment]
Thank you very much for your enthusiastic reply, I think I've found the problem, it should be a web browser problem, now I switched to chrome from IE explorer and it's downloading fine!

**Comment by maxme1** [comment]
That's great!
